/**
 * Vite SPA config for Capacitor (iOS / Android) builds.
 *
 * Unlike the main vite.config.ts which uses TanStack Start (SSR),
 * this produces a plain client-side SPA bundle that Capacitor can embed
 * in the native shell.
 *
 * Build command:  pnpm run build:spa
 * Output:         dist/  (matches capacitor.config.ts → webDir)
 *
 * Router note: the existing routeTree.gen.ts is already generated by
 * TanStack Router and works in client-only mode — no re-generation needed.
 */

import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";
import tailwindcss from "@tailwindcss/vite";
import tsconfigPaths from "vite-tsconfig-paths";
import path from "node:path";

export default defineConfig({
  plugins: [
    react(),
    tailwindcss(),
    tsconfigPaths(),
  ],

  // Resolve @/ → src/ (same as the main config)
  resolve: {
    alias: {
      "@": path.resolve(import.meta.dirname ?? __dirname, "src"),
      // Force all Node.js module imports to use our mock
      "node:async_hooks": path.resolve(import.meta.dirname ?? __dirname, "src/empty-module.js"),
      "async_hooks": path.resolve(import.meta.dirname ?? __dirname, "src/empty-module.js"),
      "node:fs": path.resolve(import.meta.dirname ?? __dirname, "src/empty-module.js"),
      "node:path": path.resolve(import.meta.dirname ?? __dirname, "src/empty-module.js"),
      "node:os": path.resolve(import.meta.dirname ?? __dirname, "src/empty-module.js"),
      "node:util": path.resolve(import.meta.dirname ?? __dirname, "src/empty-module.js"),
      "node:stream": path.resolve(import.meta.dirname ?? __dirname, "src/empty-module.js"),
      "node:events": path.resolve(import.meta.dirname ?? __dirname, "src/empty-module.js"),
    },
  },

  build: {
    outDir: "dist",
    emptyOutDir: true,
    // Produce a single-page app — all routes serve index.html
    rollupOptions: {
      input: "index.html",
      // Externalize these to prevent them from being loaded
      external: (id) => {
        return id.includes("node:") || id === "async_hooks";
      },
    },
    // Slightly larger chunk warning threshold for a feature-heavy app
    chunkSizeWarningLimit: 1200,
    commonjsOptions: {
      transformMixedEsModules: true,
      include: [/node_modules/],
    },
    rollupOptions: {
      input: "index.html",
      output: {
        // Ensure all chunks are properly handled
        manualChunks: undefined,
      },
    },
  },

  // When running vite dev for the SPA (not Capacitor live-reload):
  server: {
    port: 5173,
    host: "0.0.0.0",
    proxy: {
      // Forward /api and /socket.io to the backend during dev
      "/api": {
        target: process.env.VITE_API_URL ?? "http://localhost:3001",
        changeOrigin: true,
      },
      "/socket.io": {
        target: process.env.VITE_API_URL ?? "http://localhost:3001",
        changeOrigin: true,
        ws: true,
      },
    },
  },

  // Define global variables for browser
  define: {
    "global": "globalThis",
    "process.env": "{}",
    "process.browser": "true",
    "process.version": '""',
  },

  // Exclude problematic dependencies from optimization
  optimizeDeps: {
    exclude: [
      "@tanstack/start-storage-context",
      "node:async_hooks",
      "async_hooks",
    ],
    include: ["react", "react-dom"],
  },
});
