/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminPanelRouteImport } from './routes/admin-panel'
import { Route as AiChatRouteImport } from './routes/ai-chat'
import { Route as BlockedRouteImport } from './routes/blocked'
import { Route as CallsRouteImport } from './routes/calls'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ContactsRouteImport } from './routes/contacts'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as EditProfileRouteImport } from './routes/edit-profile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MeRouteImport } from './routes/me'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as PremiumRouteImport } from './routes/premium'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as StarredRouteImport } from './routes/starred'
import { Route as ChatIdRouteImport } from './routes/chat.$id'
import { Route as GroupIdRouteImport } from './routes/group.$id'
import { Route as JoinCodeRouteImport } from './routes/join.$code'
import { Route as UHandleRouteImport } from './routes/u.$handle'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPanelRoute = AdminPanelRouteImport.update({
  id: '/admin-panel',
  path: '/admin-panel',
  getParentRoute: () => rootRouteImport,
} as any)
const AiChatRoute = AiChatRouteImport.update({
  id: '/ai-chat',
  path: '/ai-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const BlockedRoute = BlockedRouteImport.update({
  id: '/blocked',
  path: '/blocked',
  getParentRoute: () => rootRouteImport,
} as any)
const CallsRoute = CallsRouteImport.update({
  id: '/calls',
  path: '/calls',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsRoute = ContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const EditProfileRoute = EditProfileRouteImport.update({
  id: '/edit-profile',
  path: '/edit-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MeRoute = MeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const PremiumRoute = PremiumRouteImport.update({
  id: '/premium',
  path: '/premium',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const StarredRoute = StarredRouteImport.update({
  id: '/starred',
  path: '/starred',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIdRoute = ChatIdRouteImport.update({
  id: '/chat/$id',
  path: '/chat/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupIdRoute = GroupIdRouteImport.update({
  id: '/group/$id',
  path: '/group/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinCodeRoute = JoinCodeRouteImport.update({
  id: '/join/$code',
  path: '/join/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const UHandleRoute = UHandleRouteImport.update({
  id: '/u/$handle',
  path: '/u/$handle',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin-panel': typeof AdminPanelRoute
  '/ai-chat': typeof AiChatRoute
  '/blocked': typeof BlockedRoute
  '/calls': typeof CallsRoute
  '/checkout': typeof CheckoutRoute
  '/contacts': typeof ContactsRoute
  '/discover': typeof DiscoverRoute
  '/edit-profile': typeof EditProfileRoute
  '/login': typeof LoginRoute
  '/me': typeof MeRoute
  '/notifications': typeof NotificationsRoute
  '/premium': typeof PremiumRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/starred': typeof StarredRoute
  '/chat/$id': typeof ChatIdRoute
  '/group/$id': typeof GroupIdRoute
  '/join/$code': typeof JoinCodeRoute
  '/u/$handle': typeof UHandleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin-panel': typeof AdminPanelRoute
  '/ai-chat': typeof AiChatRoute
  '/blocked': typeof BlockedRoute
  '/calls': typeof CallsRoute
  '/checkout': typeof CheckoutRoute
  '/contacts': typeof ContactsRoute
  '/discover': typeof DiscoverRoute
  '/edit-profile': typeof EditProfileRoute
  '/login': typeof LoginRoute
  '/me': typeof MeRoute
  '/notifications': typeof NotificationsRoute
  '/premium': typeof PremiumRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/starred': typeof StarredRoute
  '/chat/$id': typeof ChatIdRoute
  '/group/$id': typeof GroupIdRoute
  '/join/$code': typeof JoinCodeRoute
  '/u/$handle': typeof UHandleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin-panel': typeof AdminPanelRoute
  '/ai-chat': typeof AiChatRoute
  '/blocked': typeof BlockedRoute
  '/calls': typeof CallsRoute
  '/checkout': typeof CheckoutRoute
  '/contacts': typeof ContactsRoute
  '/discover': typeof DiscoverRoute
  '/edit-profile': typeof EditProfileRoute
  '/login': typeof LoginRoute
  '/me': typeof MeRoute
  '/notifications': typeof NotificationsRoute
  '/premium': typeof PremiumRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/starred': typeof StarredRoute
  '/chat/$id': typeof ChatIdRoute
  '/group/$id': typeof GroupIdRoute
  '/join/$code': typeof JoinCodeRoute
  '/u/$handle': typeof UHandleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin-panel'
    | '/ai-chat'
    | '/blocked'
    | '/calls'
    | '/checkout'
    | '/contacts'
    | '/discover'
    | '/edit-profile'
    | '/login'
    | '/me'
    | '/notifications'
    | '/premium'
    | '/settings'
    | '/setup'
    | '/starred'
    | '/chat/$id'
    | '/group/$id'
    | '/join/$code'
    | '/u/$handle'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin-panel'
    | '/ai-chat'
    | '/blocked'
    | '/calls'
    | '/checkout'
    | '/contacts'
    | '/discover'
    | '/edit-profile'
    | '/login'
    | '/me'
    | '/notifications'
    | '/premium'
    | '/settings'
    | '/setup'
    | '/starred'
    | '/chat/$id'
    | '/group/$id'
    | '/join/$code'
    | '/u/$handle'
  id:
    | '__root__'
    | '/'
    | '/admin-panel'
    | '/ai-chat'
    | '/blocked'
    | '/calls'
    | '/checkout'
    | '/contacts'
    | '/discover'
    | '/edit-profile'
    | '/login'
    | '/me'
    | '/notifications'
    | '/premium'
    | '/settings'
    | '/setup'
    | '/starred'
    | '/chat/$id'
    | '/group/$id'
    | '/join/$code'
    | '/u/$handle'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminPanelRoute: typeof AdminPanelRoute
  AiChatRoute: typeof AiChatRoute
  BlockedRoute: typeof BlockedRoute
  CallsRoute: typeof CallsRoute
  CheckoutRoute: typeof CheckoutRoute
  ContactsRoute: typeof ContactsRoute
  DiscoverRoute: typeof DiscoverRoute
  EditProfileRoute: typeof EditProfileRoute
  LoginRoute: typeof LoginRoute
  MeRoute: typeof MeRoute
  NotificationsRoute: typeof NotificationsRoute
  PremiumRoute: typeof PremiumRoute
  SettingsRoute: typeof SettingsRoute
  SetupRoute: typeof SetupRoute
  StarredRoute: typeof StarredRoute
  ChatIdRoute: typeof ChatIdRoute
  GroupIdRoute: typeof GroupIdRoute
  JoinCodeRoute: typeof JoinCodeRoute
  UHandleRoute: typeof UHandleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-panel': {
      id: '/admin-panel'
      path: '/admin-panel'
      fullPath: '/admin-panel'
      preLoaderRoute: typeof AdminPanelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-chat': {
      id: '/ai-chat'
      path: '/ai-chat'
      fullPath: '/ai-chat'
      preLoaderRoute: typeof AiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blocked': {
      id: '/blocked'
      path: '/blocked'
      fullPath: '/blocked'
      preLoaderRoute: typeof BlockedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calls': {
      id: '/calls'
      path: '/calls'
      fullPath: '/calls'
      preLoaderRoute: typeof CallsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts': {
      id: '/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof ContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edit-profile': {
      id: '/edit-profile'
      path: '/edit-profile'
      fullPath: '/edit-profile'
      preLoaderRoute: typeof EditProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me': {
      id: '/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof MeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/premium': {
      id: '/premium'
      path: '/premium'
      fullPath: '/premium'
      preLoaderRoute: typeof PremiumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/starred': {
      id: '/starred'
      path: '/starred'
      fullPath: '/starred'
      preLoaderRoute: typeof StarredRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$id': {
      id: '/chat/$id'
      path: '/chat/$id'
      fullPath: '/chat/$id'
      preLoaderRoute: typeof ChatIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/group/$id': {
      id: '/group/$id'
      path: '/group/$id'
      fullPath: '/group/$id'
      preLoaderRoute: typeof GroupIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join/$code': {
      id: '/join/$code'
      path: '/join/$code'
      fullPath: '/join/$code'
      preLoaderRoute: typeof JoinCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$handle': {
      id: '/u/$handle'
      path: '/u/$handle'
      fullPath: '/u/$handle'
      preLoaderRoute: typeof UHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminPanelRoute: AdminPanelRoute,
  AiChatRoute: AiChatRoute,
  BlockedRoute: BlockedRoute,
  CallsRoute: CallsRoute,
  CheckoutRoute: CheckoutRoute,
  ContactsRoute: ContactsRoute,
  DiscoverRoute: DiscoverRoute,
  EditProfileRoute: EditProfileRoute,
  LoginRoute: LoginRoute,
  MeRoute: MeRoute,
  NotificationsRoute: NotificationsRoute,
  PremiumRoute: PremiumRoute,
  SettingsRoute: SettingsRoute,
  SetupRoute: SetupRoute,
  StarredRoute: StarredRoute,
  ChatIdRoute: ChatIdRoute,
  GroupIdRoute: GroupIdRoute,
  JoinCodeRoute: JoinCodeRoute,
  UHandleRoute: UHandleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
